### ISSUE TITLE
Trinity does not limit total peer connections

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#848] opened 2018-06-01 05:36 UTC
### What is wrong?

Now that we are *useful* and staying connected to peers, a long running trinity node will acquire a **lot** of peer connections inbound, eventually swamping the node's connection.

### How can it be fixed

Finish https://github.com/ethereum/py-evm/pull/824

**Comment by gsalgado** [comment] 2018-06-01 10:34
Dupe of #771

**Closed by gsalgado** 2018-06-01 10:34 UTC
Labels: Bug, Trinity
