### ISSUE TITLE
Clean Exit

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/py-evm#827] opened 2018-05-30 16:53 UTC
### What is wrong?
`ctrl+C` on a running node should trigger a shutdown, this occurs correctly.

Getting extra error output from the terminal that should not be exposed to the user:
```bash
^CProcess Process-2:3:
Traceback (most recent call last):
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker
    call_item = call_queue.get(block=True)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
    INFO  05-30 10:31:31        main  Keyboard Interrupt: Stopping
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
    INFO  05-30 10:31:31     service  <p2p.chain.FastChainSyncer object at 0x7ff4ad6666d8> finished: Cancellation requested by RopstenFullNode token
    INFO  05-30 10:31:31       chain  Shutting down FastChainSyncer
    INFO  05-30 10:31:31       chain  Waiting for 18 running peers to finish
   ERROR  05-30 10:31:31        sync  Unclean exit from FullNodeSyncer
Traceback (most recent call last):
  File "/home/bryant/Dropbox/work/Ethereum/py-evm/p2p/sync.py", line 44, in _run
    await self._sync()
  File "/home/bryant/Dropbox/work/Ethereum/py-evm/p2p/sync.py", line 60, in _sync
    head = await self.chaindb.coro_get_canonical_head()
  File "/home/bryant/Dropbox/work/Ethereum/py-evm/trinity/utils/mp.py", line 23, in method
    args,
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/managers.py", line 756, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
    INFO  05-30 10:31:31      server  Closing server...
    INFO  05-30 10:31:31     service  <p2p.peer.PreferredNodePeerPool object at 0x7ff4a69aa2b0> finished: Cancellation requested by PreferredNodePeerPool token
    INFO  05-30 10:31:31        peer  Stopping all peers ...
    INFO  05-30 10:31:31   discovery  stopping discovery
```

### How can we fix it?
May need to catch this and handle shutdowns more gracefully.

**Comment by gsalgado** [comment] 2018-05-31 11:52
I think once #665 is fixed this will no longer happen, but not completely sure so leaving this open for now

**Comment by gsalgado** [comment] 2018-06-04 11:07
I've had a proper look into this today, and it turns out there's actually a few issues leading to it:

1. When a user hits Ctrl+C in the terminal, the [SIGINT signal is sent to the foreground process group](http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap11.html#tag_11_01_09), which means both the networking and the database processes get interrupted at the same time and not in sequence (first networking, then database) as the code in [`trinity.main()` would like](https://github.com/ethereum/py-evm/blob/master/trinity/main.py#L170-L175)
2. Our [database server catches the KeyboardInterrupt raised by the SIGINT](https://github.com/python/cpython/blob/3.6/Lib/multiprocessing/managers.py#L147-L161) shuts down and exits silently, so we don't realize but it will have already terminated by the time we run `kill_process_gracefully(database_server_process)` in `trinity.main()`
3. Thanks to the above and #665, we get the `BrokenPipeError` in the chain syncer
4. Finally, the unhandled `KeyboardInterrupt`s seem to be caused by us using the `spawn` context for the multiprocessing package. Here are the relevant passages from https://docs.python.org/3.6/library/multiprocessing.html: 
 ```
On Unix using the spawn or forkserver start methods will also start a semaphore tracker process which tracks the unlinked named semaphores created by processes of the program.
[...]
If the SIGINT signal generated by Ctrl-C arrives while the main thread is blocked by a call to BoundedSemaphore.acquire(), Lock.acquire(), RLock.acquire(), Semaphore.acquire(), Condition.acquire() or Condition.wait() then the call will be immediately interrupted and KeyboardInterrupt will be raised.
 ```

**Comment by gsalgado** [comment] 2018-06-04 14:15
So, with #860 we should no longer get the BrokenPipeErrors here, and although there seem to be other cases in which we get unhandled exceptions when shutting down I think it's better to close this once #860 is merged and create separate ones for the others (e.g. #863 and #862)

**Comment by fubuloubu** [comment] 2018-06-04 15:08
:+1: I knew there was something weird going on

**Closed** 2018-06-04 16:47 UTC
Labels: Trinity
