### ISSUE TITLE
Trinity Fails To Restart

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/py-evm#831] opened 2018-05-30 18:11 UTC
* py-evm Version: `Trinity v0.1.0-alpha.1 "Valentina Tereshkova"`
* OS: `Ubuntu 17.10`
* Python Version (python --version): `Python 3.6.3`
* Environment (output of `pip freeze`):
```
aiohttp==2.3.10
asn1crypto==0.24.0
async-lru==0.1.0
async-timeout==3.0.0
attrdict==2.0.0
backcall==0.1.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
coincurve==7.1.0
command-not-found==0.3
cryptography==2.2.2
cytoolz==0.9.0.1
decorator==4.3.0
distro-info==0.17
eth-abi==1.1.1
eth-account==0.2.3
eth-bloom==1.0.0
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-utils==1.0.3
hexbytes==0.1.0
idna==2.6
idna-ssl==1.0.1
ipython==6.4.0
ipython-genutils==0.2.0
jedi==0.12.0
keyring==10.4.0
keyrings.alt==2.2
language-selector==0.1
lru-dict==1.1.6
lxml==4.2.1
multidict==4.3.1
netdisco==1.4.1
netifaces==0.10.7
parsimonious==0.8.0
parso==0.2.1
pexpect==4.6.0
pickleshare==0.7.4
plyvel==1.0.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py-ecc==1.4.2
py-evm==0.2.0a19
pycparser==2.18
pycrypto==2.6.1
pycryptodome==3.6.1
pyethash==0.1.27
Pygments==2.2.0
pygobject==3.24.1
pysha3==1.0.2
python-apt==1.4.0b3
python-dateutil==2.7.3
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
rlp==1.0.1
SecretStorage==2.3.1
simplegeneric==0.8.1
six==1.11.0
ssh-import-id==5.7
toolz==0.9.0
traitlets==4.3.2
trie==1.3.7
trinity==0.1.0a3
ufw==0.35
unattended-upgrades==0.1
uPnPClient==0.0.8
urllib3==1.22
wcwidth==0.1.7
web3==4.2.1
websockets==5.0.1
yarl==1.2.4
zeroconf==0.20.0
```

### What is wrong?

After noting the Too many files error in #830 I stopped the process, cleaned up the logs, then attempted to restart the process, but it does not start, I just get these errors:

```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trinity/utils/logging.py", line 99, in inner
    return fn(*args, **inner_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trinity/main.py", line 136, in run_database_process
    serve_chaindb(chain_config, base_db)
  File "/usr/local/lib/python3.6/dist-packages/trinity/chains/__init__.py", line 180, in serve_chaindb
    server = manager.get_server()  # type: ignore
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 482, in get_server
    self._authkey, self._serializer)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 139, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 576, in __init__
    self._socket.bind(address)
OSError: [Errno 98] Address already in use
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trinity/utils/logging.py", line 99, in inner
    return fn(*args, **inner_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trinity/main.py", line 158, in launch_node
    node = NodeClass(chain_config)
  File "/usr/local/lib/python3.6/dist-packages/trinity/nodes/full.py", line 19, in __init__
    super().__init__(chain_config)
  File "/usr/local/lib/python3.6/dist-packages/trinity/nodes/base.py", line 54, in __init__
    self._db_manager.connect()  # type: ignore
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 489, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

### How can it be fixed

I don't know...

**Comment by pipermerriam** [comment] 2018-05-30 19:31
Related to https://github.com/ethereum/py-evm/issues/808

**Comment by MysticRyuujin** [comment] 2018-05-30 19:38
I do indeed run with supervisor and those steps did indeed allow my node to start again. Thanks, feel free to close or leave open as you see fit.

**Comment by pipermerriam** [comment] 2018-05-30 19:41
Leaving open because we need to explore how we can shutdown gracefully in situations like this.

**Comment by veox** [comment] 2018-06-08 09:27
I've experienced this without `supervisord`. Removing the dangling IPC socket files "solved" the issue for me. Forgot to check whether the `LOCK` file was still around.

**Comment by cburgdorf** [comment] 2018-06-13 07:52
Here's a somewhat hackish proposal for an *interim solution* if we can't figure how to *prevent* this from happening *just now*.

Write a command such as `repair` that can be used as `trinity repair` and basically does all the things that @pipermerriam listed above to get the node unstuck.

Any unresolved errors at startup such as the "Address already in use" error should then bring up a user friendly message that educate the user about the `trinity repair` command. I think invoking that command should always be a deliberate decision by the user and note done automatically because e.g. "Adress already in use" may be a totally legitimate thing in some situations and may not be necessarily caused by an unclean shutdown.

This is obviously more a workaround than a proper fix so I'm just throwing this idea in as an interim solution.

**Comment by pipermerriam** [comment] 2018-06-15 14:31
👍 

```
$ trinity fix_unclean_shutdown
```

**Comment by cburgdorf** [comment] 2018-06-20 07:32
It just occurred to me that even if the underlying issue that causes these unclean shutdowns is solved, such a `fix-unclean-shutdown` command still seems valuable. There are still situations (such as power outages) would lead to left ipc pipe files etc.

The most critical part of this though seems to find a cleaner way for `pkill python3` because obviously that could affect other programs as well.

Ideally, the Trinity processes would be labeled (e.g. `trinity-main`, `trinity-networking` and `trinity-database`) so that they can be identified accordingly. That said, labeling processes seems to be a messy business (also considering different OSes).

**Comment by cburgdorf** [comment] 2018-07-04 12:46
I don't think we have this specific issue anymore. Previously I was able to reproduce this quite consistently (using `trinity console`). Now, that doesn't seem to appear anymore (there have been some related fixes). 

I think we can close this issue but we may want to extract the proposed `fix-unclean-shutdown` command into a separate issue. That said, it seems more tricky than initially expected because it seems to be a pain to reliably name processes which in turn makes it quite hard to identify the processes that we want to kill.

**Comment by pipermerriam** [comment] 2018-07-04 14:18
I think we can still create a `fix-unclean-shutdown` command that is useful without the pkill part.  Maybe  just add helpful logging output to instruct the user that they **might** have to kill a running process and some basic instructions on how to do that and a big fat warning that they should know what they are doing before running `pkill` commands.

**Comment by carver** [comment] 2018-07-13 20:39
> Removing the dangling IPC socket files "solved" the issue for me.

This is weird. The socket file isn't removed for me on shutdown, but that doesn't seem to be a problem for starting trinity back up. Maybe an OS-specific behavior?

**Closed** 2018-07-17 16:53 UTC
Labels: comp: trinity, type: bug

**Comment by voith** [comment] 2019-08-02 20:19
Just making a note here in case this helps anyone in the future:

I faced this issue today while running trinity from master, when I accidentally closed my terminal.
I got the following error:
```
   ERROR  08-03 01:39:05               asyncio  Task exception was never retrieved
future: <Task finished coro=<AsyncioIsolatedPlugin._prepare_start() done, defined at /Users/voith/Projects/new-ethereum/trinity/trinity/extensibility/asyncio.py:29> exception=ConnectionRefusedError(61, 'Connection refused')>
Traceback (most recent call last):
  File "/Users/voith/Projects/new-ethereum/trinity/trinity/extensibility/asyncio.py", line 45, in _prepare_start
    self.do_start()
  File "/Users/voith/Projects/new-ethereum/trinity/trinity/plugins/builtin/syncer/plugin.py", line 296, in do_start
    node = NodeClass(self.event_bus, trinity_config)
  File "/Users/voith/Projects/new-ethereum/trinity/trinity/nodes/full.py", line 21, in __init__
    super().__init__(event_bus, trinity_config)
  File "/Users/voith/Projects/new-ethereum/trinity/trinity/nodes/base.py", line 58, in __init__
    self._db_manager = create_db_consumer_manager(trinity_config.database_ipc_path)
  File "/Users/voith/Projects/new-ethereum/trinity/trinity/db/eth1/manager.py", line 84, in create_db_consumer_manager
    manager.connect()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/managers.py", line 532, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused
```


`trinity fix-unclean-shutdown` did not work for me.

I had to do:
`rm /Users/voith/.local/share/trinity/ropsten/ipcs-eth1/*.ipc`

**Comment by carver** [comment] 2019-08-02 22:31
It should definitely clean those IPC files up for you. Master is pretty crashy right now, and I had to do the same thing earlier today.

Note that you must run the `fix-unclean-shutdown` with the same command flags as you ran the original trinity with. For example, if your `trinity --ropsten` shell crashed, then you need to run `trinity --ropsten fix-unclean-shutdown`.

**Comment by voith** [comment] 2019-08-02 22:39
> trinity --ropsten fix-unclean-shutdow

@carver Missed the ropsten flag, Thanks.
