### ISSUE TITLE
Peering with Parity - Auth msg too short: 0

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/py-evm#819] opened 2018-05-29 23:52 UTC
### What is wrong?

I run a Parity node (`Parity/v1.10.4-stable-39b9f1e-20180514/x86_64-linux-gnu/rustc1.25.0`), I added Trinity to my static-nodes list to try and force my nodes to talk to each other. However, it doesn't appear that they want to peer...

Trinity Logs:
```
   DEBUG  05-29 16:38:16      server  Receiving handshake from Address(192.168.15.32:udp:53630|tcp:53630)
   DEBUG  05-29 16:38:16      server  Failed to decrypt handshake: Auth msg too short: 0
   DEBUG  05-29 16:38:17      server  Receiving handshake from Address(192.168.15.32:udp:53718|tcp:53718)
   DEBUG  05-29 16:38:17      server  Failed to decrypt handshake: Auth msg too short: 0
   DEBUG  05-29 16:38:17      server  Receiving handshake from Address(192.168.15.32:udp:53866|tcp:53866)
   DEBUG  05-29 16:38:17      server  Failed to decrypt handshake: Auth msg too short: 0
   DEBUG  05-29 16:38:17      server  Receiving handshake from Address(192.168.15.32:udp:53934|tcp:53934)
   DEBUG  05-29 16:38:17         eth  Sending ETH/Status msg: {'protocol_version': 63, 'network_id': 1, 'td': 17179869184, 'best_hash': b'\xd4\xe5g@\xf8v\xae\xf8\xc0\x10\xb8j@\xd5\xf5gE\xa1\x18\xd0\x90j4\xe6\x9a\xec\x8c\r\xb1\xcb\x8f\xa3', 'genesis_hash': b'\xd4\xe5g@\xf8v\xae\xf8\xc0\x10\xb8j@\xd5\xf5gE\xa1\x18\xd0\x90j4\xe6\x9a\xec\x8c\r\xb1\xcb\x8f\xa3'}
   DEBUG  05-29 16:38:17      server  Could not complete handshake: ConnectionResetError(104, 'Connection reset by peer')
   DEBUG  05-29 16:38:18      server  Receiving handshake from Address(192.168.15.32:udp:54064|tcp:54064)
   DEBUG  05-29 16:38:18         eth  Sending ETH/Status msg: {'protocol_version': 63, 'network_id': 1, 'td': 17179869184, 'best_hash': b'\xd4\xe5g@\xf8v\xae\xf8\xc0\x10\xb8j@\xd5\xf5gE\xa1\x18\xd0\x90j4\xe6\x9a\xec\x8c\r\xb1\xcb\x8f\xa3', 'genesis_hash': b'\xd4\xe5g@\xf8v\xae\xf8\xc0\x10\xb8j@\xd5\xf5gE\xa1\x18\xd0\x90j4\xe6\x9a\xec\x8c\r\xb1\xcb\x8f\xa3'}
   DEBUG  05-29 16:38:18      server  Could not complete handshake: ConnectionResetError(104, 'Connection reset by peer')
   DEBUG  05-29 16:38:19      server  Receiving handshake from Address(192.168.15.32:udp:54152|tcp:54152)
   DEBUG  05-29 16:38:19         eth  Sending ETH/Status msg: {'protocol_version': 63, 'network_id': 1, 'td': 17179869184, 'best_hash': b'\xd4\xe5g@\xf8v\xae\xf8\xc0\x10\xb8j@\xd5\xf5gE\xa1\x18\xd0\x90j4\xe6\x9a\xec\x8c\r\xb1\xcb\x8f\xa3', 'genesis_hash': b'\xd4\xe5g@\xf8v\xae\xf8\xc0\x10\xb8j@\xd5\xf5gE\xa1\x18\xd0\x90j4\xe6\x9a\xec\x8c\r\xb1\xcb\x8f\xa3'}
   DEBUG  05-29 16:38:19      server  Could not complete handshake: ConnectionResetError(104, 'Connection reset by peer')
   DEBUG  05-29 16:38:20      server  Receiving handshake from Address(192.168.15.32:udp:54248|tcp:54248)
   DEBUG  05-29 16:38:20      server  Could not complete handshake: ConnectionResetError(104, 'Connection reset by peer')
   DEBUG  05-29 16:38:21      server  Receiving handshake from Address(192.168.15.32:udp:54326|tcp:54326)
   DEBUG  05-29 16:38:21      server  Could not complete handshake: ConnectionResetError(104, 'Connection reset by peer')
   DEBUG  05-29 16:38:21      server  Receiving handshake from Address(45.77.102.136:udp:50032|tcp:50032)
   DEBUG  05-29 16:38:21      server  Could not complete handshake: No matching capabilities between us ([('eth', 63)]) and <Node(0x1a7e@45.77.102.136)> ((('les', 1),)), disconnecting
```

### How can it be fixed

No Idea

**Comment by MysticRyuujin** [comment] 2018-05-30 00:02
Probably related to #718 ?

**Comment by gsalgado** [comment] 2018-05-30 08:17
Looks like a dupe of #776, actually, although in this case it's an incoming handshake whereas there it's outgoing

**Comment by MysticRyuujin** [comment] 2018-05-30 18:15
Yeah, it looks like maybe my enode id changed from my first run and I didn't catch it. I'm not able to start my node right now 😄 but I'll re-open if it turns out it's still an issue after. Sorry!

**Comment by MysticRyuujin** [comment] 2018-05-30 19:42
Ok I'm re-opening because I'm not sure what this is about:

```
INFO  05-30 12:37:42        main  enode://9bd6a447395b6a007e71085da1c1fa71422fb4d25808ec9c5d7532ecfb6e3040@[:]:30304
    INFO  05-30 12:37:42        main  network: 1
    INFO  05-30 12:37:42         ipc  IPC started at: /root/trinity/$HOME/.local/share/trinity/mainnet/jsonrpc.ipc
    INFO  05-30 12:37:42      server  Running server...
    INFO  05-30 12:37:47      server  No UPNP-enabled devices found
    INFO  05-30 12:37:47      server  enode://f902b8271331ba21c1c93c6f4c1e2cfcfb883200286278b7400e712922d4aa7b5c39796df1c3c75dbbfcb96d20d8c70d759bda2a9d5fb204c7bcdf4d9abc42c0@0.0.0.0:30304
```

What is my node ID and why are there two of them in my log?
`enode://9bd6a447395b6a007e71085da1c1fa71422fb4d25808ec9c5d7532ecfb6e3040@[:]:30304` seems too short?
`enode://f902b8271331ba21c1c93c6f4c1e2cfcfb883200286278b7400e712922d4aa7b5c39796df1c3c75dbbfcb96d20d8c70d759bda2a9d5fb204c7bcdf4d9abc42c0@0.0.0.0:30304` is a different enode?

**Comment by pipermerriam** [comment] 2018-05-30 20:17
@MysticRyuujin 

That first one is your private key (sorry!!!).  We had a bug that was dumping nodekeys into the terminal (and logging) output.  You should be able to remove your nodekey file and trinity will generate a new one gracefully.

```bash
rm ~/.local/share/trinity/mainnet/nodekey`
```

**Comment by pipermerriam** [comment] 2018-05-30 20:18
The `0.0.0.0` is hard coded right now and not necessarily representative of the address that Trinity thinks it is connected to.

**Comment by MysticRyuujin** [comment] 2018-05-30 20:21
I have no intention of using that private key haha but that's good to know!

So the issue still stands then, as I was using the correct enode ID - it's still accurate.

I can try it out again and get back to you...

**Comment by MysticRyuujin** [comment] 2018-05-30 20:40
I deleted everything (database included) and updated to `0.1.0a5` and now I'm not peering with anyone. I definitely updated my enode ID after restarting on both my Geth and Parity nodes, but I get theses:

```
   DEBUG  05-30 13:28:00      server  Receiving handshake from Address(192.168.15.32:udp:43800|tcp:43800) <--- Parity
   DEBUG  05-30 13:28:02      server  Receiving handshake from Address(192.168.15.31:udp:35642|tcp:35642) <--- Geth
   DEBUG  05-30 13:32:08      server  Failed to decrypt handshake: Failed to verify tag
```

Also my running process just keeps saying I have 0 inbound peers

**Comment by gsalgado** [comment] 2018-06-06 15:16
@MysticRyuujin can you share the enode of your Parity node so I can try and reproduce/debug?

**Comment by MysticRyuujin** [comment] 2018-06-06 15:22
@gsalgado my home network is dead right now - I'm in the process of moving 😄 if you're not having issues with Parity peering and 'it's just me' then I can re-evaluate in a week or so if I'm still having issues - I know development is happening quickly - and I'd hate to waste your time.

**Comment by pipermerriam** [comment] 2018-06-06 15:52
@gsalgado working on getting us a parity node for testing.

**Comment by gsalgado** [comment] 2018-06-07 15:16
So, I've spent most of today on this and although I haven't managed to connect to a Parity node yet, I at least have a better idea of what is going on. First, we have a bug in `p2p.Server`, which always replies with a plain auth-ack even when it receives an EIP8 auth msg. However, even when we reply with an EIP8 auth-ack, parity still disconnects from us as soon as it receives our Hello message. I'm trying to get help from Parity developers because it's not easy to figure out what exactly is causing Parity to behave this way

**Closed** 2018-06-12 14:07 UTC
Labels: p2p
